### ISSUE TITLE
DB 연결 

### ISSUE THREAD

**Issue by haileyKimDev** [f-lab-edu/board#4]
- [x] application.properties 설정
- [x] 유저 데이터 조회

@hoa0217 DB 연결 확인을 위해 컨트롤러에  getUser메소드를 추가했습니다.
http -v ":8080/users/jeonghwa/exists"  으로 호출하면 다음과 같이 결과값이 확인됩니다.

> HTTP/1.1 200 
Connection: keep-alive
Content-Type: application/json
Date: Tue, 14 Mar 2023 18:27:58 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

> 
> {
>     "createDate": "2023-02-16T01:17:54",
>     "email": "gjwjdghk123@gmail.com",
>     "name": "jeonghwa",
>     "nickName": "jjeong",
>     "password": "sceretkey",
>     "updateDate": null,
>     "userId": 1,
>     "userStatus": "NORMAL"
> }

**Comment by haileyKimDev** [comment]
DB정보 설정한 커밋은 아래 링크입니다.
커밋을 수정한 내용이 반영이안되는것 같네요 ㅠ ㅠ 
[커밋](https://github.com/f-lab-edu/s-mart/commit/4b8baba435505fbf19f88a8596f14ef881c960ac)

**Comment by hoa0217** [comment]
영화님 수고하셨습니다 🙂
